package be.rubenpieters.datetime4s

import java.time.LocalDate
import java.time.format.DateTimeFormatterBuilder.ReducedPrinterParser
import java.time.format.{DateTimeFormatterBuilder, SignStyle, TextStyle}
import java.time.temporal.{ChronoField, TemporalField}

/**
  * Created by ruben on 4/10/2016.
  */
sealed trait FormatterField {
  def append(dateTimeFormatterBuilder: DateTimeFormatterBuilder)
}

final case class LiteralString(literal: String) extends FormatterField {
  override def append(dateTimeFormatterBuilder: DateTimeFormatterBuilder): Unit = {
    dateTimeFormatterBuilder.appendLiteral(literal)
  }
}

final case class LiteralChar(literal: Char) extends FormatterField {
  override def append(dateTimeFormatterBuilder: DateTimeFormatterBuilder): Unit = {
    dateTimeFormatterBuilder.appendLiteral(literal)
  }
}

sealed trait PredefinedPatternFormatterField extends FormatterField {
  def pattern: String

  override def append(dateTimeFormatterBuilder: DateTimeFormatterBuilder): Unit = {
    dateTimeFormatterBuilder.appendPattern(pattern)
  }
}

// AUTOGENERATED BY FormatterFieldsCodeGen

case object Era1 extends PredefinedPatternFormatterField {
  override val pattern = "G"
}

case object Era2 extends PredefinedPatternFormatterField {
  override val pattern = "GG"
}

case object Era3 extends PredefinedPatternFormatterField {
  override val pattern = "GGG"
}

case object Era4 extends PredefinedPatternFormatterField {
  override val pattern = "GGGG"
}

case object Era5 extends PredefinedPatternFormatterField {
  override val pattern = "GGGGG"
}

case object Year1 extends PredefinedPatternFormatterField {
  override val pattern = "u"
}

case object Year2 extends PredefinedPatternFormatterField {
  override val pattern = "uu"
}

case object Year3 extends PredefinedPatternFormatterField {
  override val pattern = "uuu"
}

case object YearEP extends PredefinedPatternFormatterField {
  override val pattern = "u..u"
}

case object YearOfEra1 extends PredefinedPatternFormatterField {
  override val pattern = "y"
}

case object YearOfEra2 extends PredefinedPatternFormatterField {
  override val pattern = "yy"
}

case object YearOfEra3 extends PredefinedPatternFormatterField {
  override val pattern = "yyy"
}

case object YearOfEraEP extends PredefinedPatternFormatterField {
  override val pattern = "y..y"
}

case object WeekBasedYear1 extends PredefinedPatternFormatterField {
  override val pattern = "Y"
}

case object WeekBasedYear2 extends PredefinedPatternFormatterField {
  override val pattern = "YY"
}

case object WeekBasedYear3 extends PredefinedPatternFormatterField {
  override val pattern = "YYY"
}

case object WeekBasedYearEP extends PredefinedPatternFormatterField {
  override val pattern = "Y..Y"
}

case object QuarterOfYear1 extends PredefinedPatternFormatterField {
  override val pattern = "Q"
}

case object QuarterOfYear2 extends PredefinedPatternFormatterField {
  override val pattern = "QQ"
}

case object QuarterOfYear3 extends PredefinedPatternFormatterField {
  override val pattern = "QQQ"
}

case object QuarterOfYear4 extends PredefinedPatternFormatterField {
  override val pattern = "QQQQ"
}

case object QuarterOfYear5 extends PredefinedPatternFormatterField {
  override val pattern = "QQQQQ"
}

case object QuarterOfYearTxt1 extends PredefinedPatternFormatterField {
  override val pattern = "q"
}

case object QuarterOfYearTxt2 extends PredefinedPatternFormatterField {
  override val pattern = "qq"
}

case object QuarterOfYearTxt3 extends PredefinedPatternFormatterField {
  override val pattern = "qqq"
}

case object QuarterOfYearTxt4 extends PredefinedPatternFormatterField {
  override val pattern = "qqqq"
}

case object QuarterOfYearTxt5 extends PredefinedPatternFormatterField {
  override val pattern = "qqqqq"
}

case object MonthOfYear1 extends PredefinedPatternFormatterField {
  override val pattern = "M"
}

case object MonthOfYear2 extends PredefinedPatternFormatterField {
  override val pattern = "MM"
}

case object MonthOfYear3 extends PredefinedPatternFormatterField {
  override val pattern = "MMM"
}

case object MonthOfYear4 extends PredefinedPatternFormatterField {
  override val pattern = "MMMM"
}

case object MonthOfYear5 extends PredefinedPatternFormatterField {
  override val pattern = "MMMMM"
}

case object MonthOfYearTxt1 extends PredefinedPatternFormatterField {
  override val pattern = "L"
}

case object MonthOfYearTxt2 extends PredefinedPatternFormatterField {
  override val pattern = "LL"
}

case object MonthOfYearTxt3 extends PredefinedPatternFormatterField {
  override val pattern = "LLL"
}

case object MonthOfYearTxt4 extends PredefinedPatternFormatterField {
  override val pattern = "LLLL"
}

case object MonthOfYearTxt5 extends PredefinedPatternFormatterField {
  override val pattern = "LLLLL"
}

case object WeekOfWeekBasedYear1 extends PredefinedPatternFormatterField {
  override val pattern = "w"
}

case object WeekOfWeekBasedYear2 extends PredefinedPatternFormatterField {
  override val pattern = "ww"
}

case object WeekOfMonth1 extends PredefinedPatternFormatterField {
  override val pattern = "W"
}

case object DayOfMonth1 extends PredefinedPatternFormatterField {
  override val pattern = "d"
}

case object DayOfMonth2 extends PredefinedPatternFormatterField {
  override val pattern = "dd"
}

case object DayOfYear1 extends PredefinedPatternFormatterField {
  override val pattern = "D"
}

case object DayOfYear2 extends PredefinedPatternFormatterField {
  override val pattern = "DD"
}

case object DayOfYear3 extends PredefinedPatternFormatterField {
  override val pattern = "DDD"
}

case object AlignedDayOfWeekInMonth1 extends PredefinedPatternFormatterField {
  override val pattern = "F"
}

case object DayOfWeek1 extends PredefinedPatternFormatterField {
  override val pattern = "E"
}

case object DayOfWeek2 extends PredefinedPatternFormatterField {
  override val pattern = "EE"
}

case object DayOfWeek3 extends PredefinedPatternFormatterField {
  override val pattern = "EEE"
}

case object DayOfWeek4 extends PredefinedPatternFormatterField {
  override val pattern = "EEEE"
}

case object DayOfWeek5 extends PredefinedPatternFormatterField {
  override val pattern = "EEEEE"
}

case object Localized1 extends PredefinedPatternFormatterField {
  override val pattern = "e"
}

case object Localized2 extends PredefinedPatternFormatterField {
  override val pattern = "ee"
}

case object Localized3 extends PredefinedPatternFormatterField {
  override val pattern = "eee"
}

case object Localized4 extends PredefinedPatternFormatterField {
  override val pattern = "eeee"
}

case object Localized5 extends PredefinedPatternFormatterField {
  override val pattern = "eeeee"
}

case object LocalizedTxt1 extends PredefinedPatternFormatterField {
  override val pattern = "c"
}

case object LocalizedTxt3 extends PredefinedPatternFormatterField {
  override val pattern = "ccc"
}

case object LocalizedTxt4 extends PredefinedPatternFormatterField {
  override val pattern = "cccc"
}

case object LocalizedTxt5 extends PredefinedPatternFormatterField {
  override val pattern = "ccccc"
}